#route:
#  group_by: ['alertname']
#  group_wait: 30s
#  group_interval: 5m
#  repeat_interval: 1h
#  receiver: 'email'
#receivers:
#  - name: "email"
#    email_configs:
#      - to: "tilak.04@yahoo.com"
#        from: "tilak.04@yahoo.com"
#        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
#        auth_username: "{{SES_USER}}"
#        auth_password: "{{SES_PASS}}"
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']